POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Hessun blogi",
    "author": "Hessu",
    "url": "hessu.fi",
    "likes": 543,
    "userId": "5f2d36c69933b9241c19ac29"
    
}